#server.port=8081
#spring.application.name=nacos-provider
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#management.endpoints.web.exposure.include=*
server:
  port: 9001




spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
#    url: jdbc:mysql://localhost:3306/SpringCloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
          # 名称随意
        flow:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}-flow-rules
              groupId: SENTINEL_GROUP
              # 规则类型，取值见：
              # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
              rule-type: flow
        degrade:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}-degrade-rules
              groupId: SENTINEL_GROUP
              rule-type: degrade
        system:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}-system-rules
              groupId: SENTINEL_GROUP
              rule-type: system
        authority:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}-authority-rules
              groupId: SENTINEL_GROUP
              rule-type: authority
        param-flow:
            nacos:
              server-addr: localhost:8848
              dataId: ${spring.application.name}-param-flow-rules
              groupId: SENTINEL_GROUP
              rule-type: param-flow

#  spring.cloud.sentinel.datasource.ds2.nacos.server-addr=localhost:8848
#  spring.cloud.sentinel.datasource.ds2.nacos.data-id=sentinel
#  spring.cloud.sentinel.datasource.ds2.nacos.group-id=DEFAULT_GROUP
#  spring.cloud.sentinel.datasource.ds2.nacos.data-type=json
#  spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade

management:
  endpoints:
    web:
      exposure:
        include: '*'