#server.port=8081
#spring.application.name=nacos-provider
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#management.endpoints.web.exposure.include=*
server:
  port: 9001




spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
#    url: jdbc:mysql://localhost:3306/SpringCloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'